server:
  port: 8082
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8


  jsp-servlet:
    init-parameters:
      development: true

spring:
  profiles:
    active: dev
  message:
    encoding: UTF-8
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    auto: true
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mybatis_mysql/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lcms.*.*.*.domain.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #驼峰下划线转换
      column-underline: true
      #db-type: mysql
      #修改字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      update-strategy: NOT_EMPTY
      #新增字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      insert-strategy: NOT_EMPTY
    banner: false
    #AR 模式
    activeRecord: true
  #原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler